### ISSUE TITLE
Do not load preview of all folders in current folder

### ISSUE THREAD

**Issue by vestingz** [Libresonic/libresonic#114]
Currently, Libresonic seems to be generating a list of all available subfolders containing playable files in "Playing View", which are being displayed below the currently playing release. This causes Libresonic to substantially lag on bigger collections (checked for folders containing 1000+ subfolders). Is there any setting to disable this behaviour?

**Comment by EugeneKay** [comment]
Can you provide an example URL of the frame or take a screenshot of the page that you are describing? I'm not certain exactly which view it is that you're experiencing issues with. I have not run into serious performance problems with my library(~150GB / 23,000 entries), but I also have fast hardware and disks.

**Comment by vestingz** [comment]
![bildschirmfoto vom 2016-07-19 23-31-14](https://cloud.githubusercontent.com/assets/19933361/16967615/11079472-4e0a-11e6-90c8-8e0e3b46a8c6.png)
![bildschirmfoto vom 2016-07-19 23-34-27](https://cloud.githubusercontent.com/assets/19933361/16967614/11045d2a-4e0a-11e6-8c48-b37e00ec6ec4.png)
The URL would be /libresonic/index.view.
Libresonic/Tomcat is running on 2.8GHz/8GB Ram/SSD, with all the files stored on a 3-Disk-RAIDZ-Array. But indeed, accessing this view causes almost 100% CPU load on my laptop for a few seconds.

**Comment by DaveWut** [comment]
If I'm not wrong, why this is lagging on your laptop and not on the server is because the list of folders and files to play are generated using javascript. This causes to make your browser load and render everything and not the server. I have a folder containing more than 2800 songs and I have the same problem. Plus, scrolling into this page lags a little. 

Excepts if the rendering methods are rewritten, this won't change for certain period of time. Maybe if you browse your library using another computer (and a more powerful one) it might be better.

**Comment by vestingz** [comment]
Yes, totally makes sense considering my server barely showing any activity while i access these pages.
Other then rewriting the rendering methods, wouldn't it be possible to disable the folder listing/reduce it to a default amount of five (eg most similar) with the option to load more?

**Comment by DaveWut** [comment]
This feature is partially implemented on Subsonic 6.0. When the folder contains too much sub folders, it will display a partial list, then offers the user to show the rest using a button (Show all albums): https://i.imgur.com/fWZY7ob.png. Maybe the same thing can be implemented and could be done too when a folder contains too much songs.

**Comment by vestingz** [comment]
Libresonic actually behaves the same as far is i can tell. Still, Libresonic seems to create an exhaustive list of all albums (or better: subfolders containing playable media) found on the same directory level as the one it is currently playing. "Show all albums" in Libresonic seems only to unfold this already created list.

Today, Firefox offered me to stop following script for being unresponsivewhen unfolding a list of 1500+ subfolders: jquery-1.7.1.min.js:3

**Comment by DaveWut** [comment]
The big problem here is the usage of javascript to generate the list. Using the server to load the list could take less time. So here's the thing I note that might improve the product: 

- Load the list of songs and folders using the server
- Create a configurable parameter in the settings to limit the number of songs / folders to display per page
- Limit the number of songs / folders to display based on the setting
- Show a button "Load everything"
- Show a button "Load more" which would loads another chunk of songs / folders limited on the previously configured setting

**Comment by muff1nman** [comment]
Really I think pagination should be redone across the board in order to properly implement "Load More" and do so seamlessly in JavaScript. However for now, I think it might be possible to get at least a bandaid fix out for 6.2 with somewhat simplified behavior that does simplistic pagination server side:

Initial load, loads up to X number of subDirs/siblingAlbums. A "show all" button is shown at the bottom. If it is clicked, the page reloads showing all subDirs/siblingAlbums. No javascript - all server side.

**Comment by muff1nman** [comment]
Should X be a user setting or an across the board setting for the admin to manage?

**Comment by muff1nman** [comment]
Although there are more improvements to be done with regards to pagination, #292 should take most of the pain away for the short term.
