### ISSUE TITLE
UPnP Deprecation

### ISSUE THREAD

**Issue by tob123** [Libresonic/libresonic#162]
Hi,

libresonic is a great initiative. tried out the 6.1 stable release and most things look pretty good to me!
only thing i found non working for me is upnp. the libresonic 6.2 release plan mentions it would be carved out. But: i use it quite a lot: mostly for sending audio from subsonic (the upnp server) to my raspberry PI ( the upnp renderer) via my phone or tablet (the upnp controller).
Can upnp pretty please be fixed and / or kept in ?

best regards,

Tobias.

**Comment by biconou** [comment]
Hi @tob123 and welcome to libresonic !
I would like to reply exactly to your question. 
I agree with @EugeneKay : UpnP does not worth the effort. I think it is sort of standard technology that will never work properly.
We can consider better alternatives even with your use case.
Libresonic has a jukebox feature that means you can play music directly on the server hosting libresonic rather than in streaming mode. Unfortunately, the jukebox system has some downsides. 
Fortunately, I am currently working on a jukebox system that really works. 
But, in your case, I suppose that your Libresonic is not hosted on your Pi but that your Pi is combined to a DAC to play music on your stereo system. So you just need a sort of remote jukebox system. 
Fortunately again, I developed on my own Subsonic fork such a system.
I host Subsonic on a Pi, send the music on another Pi and drive the hole system with my phone using Ultrasonic (even work with the official Subsonic android app).
I first develop a very efficient version based on the cmus music player that can be controlled remote. I will probably bring it to libresonic. But I am also thinking of developing a remote jukebox player inside libresonic. 

Tell us if it seems nice for you.

**Comment by muff1nman** [comment]
Although I don't have any need for upnp, I am actually in agreement with @tob123. Upnp can be a useful feature for interoperability with "smart" devices that solely implement upnp/dnla. I am well aware of the security nightmares associated with Upnp, but those concerns are mostly associated with your router. If users have upnp enabled on their router, they have other problems. Rather than ripping the feature out entirely, it would make more sense to make it a toggle-able feature that is disabled by default.

**Comment by biconou** [comment]
@muff1nman You are probably wright. I don't know Upnp verry well but the few times I tried to test it, it was very slow.

**Comment by tob123** [comment]
Hi, glad to read quite some folks are onboard to talk on this.
I absolutely agree that upnp has its pitfalls on a security level but i have no expecations to use the upnp server via internet. My own expecations on streaming etc. (if this can be done with other solutions than upnp I would really like to know!):
strict requirement 1: as biconou describes: control play from phone with decent app that can do ad hoc playlist management (drag / drop) and allows both folder based / tag based overviews.
strict requirement 2: audio play needs to be losless or hi-res (aka if there is flac on the phone or libresonic server) it needs to be played losless on my audio device.
strict requirement 3: support gapless playback.
less strict requirement a: show nice artwork / current playlist on tv
less strict requirement b: support replaygain

constraint I: setup needs to be compatible to old stereo set / tv:
---i have no receiver that supports hdmi ( i have an old amplifier, but quality is good)
---my tv does support hdmi but i do not want to route normal tv watching through my stereo (only watching movies or listening to music). tv does not support switching between hdmi / tv boxes. 

solution I have in place: libresonic, dsub aondroid app and kodi on raspberry pi with hifiberry DAC. it actually does not meet all requirements because gapless playback and replaygain is not handled well; 
There is a small gap between each track and replaygain does not work..

any suggestions for improvements:
very very much appreciated!

regards,

Tobias.

**Comment by biconou** [comment]
@tob123 The new jukebox I am working on is gapless, supports lossless (mainly flac) and Hi resolution audio files without downsampling. It is designed for people like you, I mean real audiopliles.

**Comment by tob123** [comment]
ok. sounds very good biconou..! 
i think your setup suggests to run the libresonic and the player connected to the dac on the same device ?. that should definitely work..!
if i understand your setup; anything i can do to help ? my programming skills are not very good, (mostly did perl script writing / bash script writing)

only thing i might need to do is getting another raspberry PI to keep using kodi based stuff but that is perfectly fine.

few more things that might be a concern..: 
1) i currently host the subsonic server on a system that is a bit more powerful (desktop that acts like a server) but speed i saw with subsonic on a pi is good enough for me. only some rescanning work might become slower but i do not do that very often.
2) desktop also supports some other publicly accessible websites so need to do some things with forwarding correct traffic for libresonic website to pi vs other websites to other system. seems doable with some modproxy stuff.

**Comment by biconou** [comment]
@tob123 If you want to help, a good idea woould be to be a tester of the fukebox features I am coding. 
As you I am an audiophile and need a good player system to take advandage of high quality DACs. 
My first motivation to work on Subsonic was to leverage it to a high quality audio player.

I run my subsonic on a bananaPi that is a sort of raspberryPi with a SATA connector. Very good solution.

**Comment by tob123** [comment]
ok. sounds good. i am certainly willing to test things out. where do i start ?

**Comment by biconou** [comment]
I should create a branch for you so I'll can test it. Not immediately cause I am working on Spring migration. 
Just follow this thread.

**Comment by EugeneKay** [comment]
UPnP is a huge security problem for the internet, mostly in the form of botnets exploiting port-forwards to take-over insecure IoT devices. I realize that Libresonic is not a huge target, but I do not want to have anything to do with such a crappy technology and the implications involved. DLNA(local streaming) will also be deprecated due to a lack of device testing and perceived usage. Newer technologies(eg, Chromecast) take security seriously and seem to work better. I would like to reimplement the MediaRouter API to fix Casting support, which is a separate problem entirely.

I'm leaving this issue open to discuss & document alternate solutions for local streaming.

**Comment by muff1nman** [comment]
I agree with you that upnp can be a problem from a security perspective, but only if people have it enabled on their router. I feel that we should take a bit more conservative approach to features that I feel users are using as exampled by @tob123. I have a feeling there are some users that are using the discovery feature of upnp/dlna over their local lan without even knowing. I use a chromecast myself, but for many, upnp/dlna is easier and cheaper as they already have devices supporting these technologies. 

Can we instead make a by-default-disabled feature?

**Comment by nicosalto** [comment]
Hi, 
i bring my ideas to the table. i am an audiophile as well, and i have a microrendu (MPD headless player) connected to my DAC. Currently i am controlling the music playing with Mpad app on ipad, but it is less than ideal... Personnally i really like madsonic to manage the music library, and i havnt tried libresonic yet. But if libresonic could integrate an MPD player that control a remote control an MPD instance on the network i would definitely switch to it!
To me it would be amazing because it would mean playing high quality (flac) directly to mpd and gapless play back with a great web interface. And i think a lot of audiophile would be interested. At the moment only roon does this kind of things on the market (https://roonlabs.com/), I've also tested Ampache, but their implementation is really terrible.

**Comment by jooola** [comment]
@nicosalto I don't think you're post is right here BUT, here is a answer 

Correct me if i'm wrong but libresonic still have a jukebox feature right ?

If you have a libresonic instance running plugged in your speakers you can connect through the web UI and use it as a remote control for the server.
The BUT for you will be that Flac may be trans-coded but i don't know if this is a Network speed problem or a compatibility problem.

**Comment by muff1nman** [comment]
Upnp is perfectly functional in 6.1 and I see no reason to remove it

**Comment by muff1nman** [comment]
Let me clarify that the dnla functionality is functional. The port forwarding/router registration stuff should be removed and #260 does just that.

**Comment by muff1nman** [comment]
With port forwarding removed, I'm marking this as resolved. Dnla will be kept for niw

**Comment by biconou** [comment]
@tob123 @nicosalto 
I created a pull request #277  for a new jukebox feature that may meet your needs
