### ISSUE TITLE
Not an issue just a question about installation

### ISSUE THREAD

**Issue by djdmd** [Libresonic/libresonic#208]
Hello 
I used to install subsonic and after libresonic by compiling and having a .deb package to install on my raspberry . I have tryied to install a tomcat and the war package but it used 100% cPU to deploy the war package and i cannot start it.

Finally my question is  : is there a way to compile and have a .deb package ?

Thx

**Comment by fxthomas** [comment]
I realize this is only really visible on the `develop` branch (until 6.2 is released) : [here](https://github.com/Libresonic/libresonic/blob/develop/documentation/BUILD.md) are the build instructions for all kinds of packages.

Ideally I think we should be able to provide Debian/RPM packages in addition to the .war for each release.

**Comment by EugeneKay** [comment]
I historically did not provide a deb/RPM(or exe) target for subsonic-kang because I don't use those methods and I am frankly not that interested. The BUILD.md linked _ought_ to work for you. Long term it is likely that packaging will be improved and an official build will be released against other targets, but today is not that day.
