### ISSUE TITLE
Random play yields no songs at all

### ISSUE THREAD

**Issue by ilmagico** [Libresonic/libresonic#250]
I just upgraded Libresonic from 6.0.1 to 6.1, and the "Random" view on the web UI (default view in home page) shows no songs at all. Hitting "Shuffle" on the player does nothing.
Even using a player on android (UltraSonic), trying to play random returns a "No media found" error.

I first tried by migrating the /var/subsonic directory into /var/libresonic, and then I also tried to start from scratch, same result.

**Comment by ilmagico** [comment]
![screenshot from 2017-02-16 18-13-48](https://cloud.githubusercontent.com/assets/7019416/23034467/d2056496-f473-11e6-85ce-ea511cc40f63.png)
This is the home page on the Random tab

**Comment by fxthomas** [comment]
Did you rescan your library?

**Comment by ilmagico** [comment]
I actually started from scratch, deleting (well, moving) /var/libresonic and making a new one, adding the media folder, which I'm sure triggers a scan, because artists and albums were populated (as you can see on the left of the screenshot). 
In any case, I did force a media scan, and sure enough, the page was populated... thanks, hopefully it stays this way!

**Comment by fxthomas** [comment]
Given the results I'm fairly sure Libresonic does not rescan when you add a media folder, then :)

Libresonic will automatically "refresh" contents from visited folders. That's probably why you cannot see anything in the Random view (because there's nothing yet in the database), but you can see directories in the sidebar (because Libresonic is noticing them in your root media folder).

**Comment by muff1nman** [comment]
Closing as it sounds like this is resolved.
