### ISSUE TITLE
Add meta name="robots" and robots.txt 

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#284]
I suggest to add a way to change the following meta parameters in the libresonic settings:
`<meta name="robots" content ="none">`
And why not adding a robots.txt file that by default disallow any crawling agent.

Since libresonic is supposed to be for personal use i don't want it to be displayed in public.
This is just a suggestion but i think this could be useful !

**Comment by EugeneKay** [comment]
robots.txt is useless on the modern web and I think this is a waste of time. Even the Internet Archive has stopped respecting them. If you would like to secure your Libresonic installation against crawling you should use HTTP Basic Authentication(in a reverse-proxy in front of Libresonic), or otherwise block crawls at a lower level - this is not Libresonic's job.
