### ISSUE TITLE
Custom domain option gone for good?

### ISSUE THREAD

**Issue by SuperNerd-James** [Libresonic/libresonic#443]
Why does the custom domain option seem to have disappeared? I don't mean the premium "yourdomain.subsonic.org" option that required premium, but the one where you can use your own? That was a free option that stayed working even when Premium expired on the old SubSonic, so I can't see why it has been removed.

This is what SubSonic looks like on my server:

![subsonic custom domain](https://cloud.githubusercontent.com/assets/2358163/26563518/285bc75c-44cb-11e7-8c60-ac244c7a3353.jpg)

I run a private streaming server for my staff on a subdomain of our main domain, using SubSonic 6, at songshark.kitamuracomputers.net on Windows Server with Active Directory which is internet facing. I cannot do this with LibreSonic, it just refuses to connect if I use the same domain. Taking the full custom domain option out is a dealbreaker for me. I really want to ditch SubSonic, but the lack of this domain option, and a proper keyboard shortcut supporting HTML 5 player like the one SS6 has is putting me off.

**Comment by SuperNerd-James** [comment]
The Network tab is completely missing on the latest build of LS:
![libresonic-network-tab-missing](https://cloud.githubusercontent.com/assets/2358163/26563651/019938aa-44cd-11e7-8b53-579be84bebf2.jpg)

**Comment by jooola** [comment]
I think more that you didn't made this work yet.
I'm actually running libresonic and accessing it through : https://audio.mydomain.tld
There is no need to add any settings within libresonic. Everything is setup externally.
The libresonic front end could be `audio.mydomain.tld` or `mydomain.tld` this will work the same since the back end simply listen at `127.0.0.1:8080/`.

Could you past you're configurations somewhere we can read them ?

**Comment by muff1nman** [comment]
Ignore @jooola  for a second (sorry @jooola and thanks for helping out as always :)

So digging up some history here, we have #93 #239 and #260. I would peruse through those, but to summarize custom url redirection was removed because it was cumbersome and we thought we could achieve the same thing without it at all. Or to be more precise, url redirection was basically just used for creating external urls, like the share url. The thought was that we could correctly create these external urls using the same `Host` that the user is using to access the site in the first place. The only exception is that we would be mindful of any proxy directives to use a different url in the case we are behind a proxy where `Host` is not reliable.

So without the url redirection service, without needing custom url and with the removal of port forwarding being done by libresonic in #162 and #260, there was no need for the Network Tab.

> I cannot do this with LibreSonic, it just refuses to connect if I use the same domain.

So I assume you are having problems just hitting the login page. If so, your issue is not with custom url redirection, but more with the fact that upnp port forwarding support was removed. So I would just open a http port to achieve the same effect.

**Comment by SuperNerd-James** [comment]
I managed to partially fix the issue. I have three layers to our infrastructure. My domain registrar's A hosts, my server's Active Directory A hosts (which have to match the registrar for domain) and then router ports. The router had updated itself sometime recently, and not rebooted cleanly, port 8080 wasn't open even though the firewall said it was!

But, now, outside the network, with a fresh install, and a new C:\libresonic folder setup, after booting the server and attempting to login, I get this:

![libresonic-login-error](https://cloud.githubusercontent.com/assets/2358163/26564005/76572746-44d3-11e7-84a2-07772ae11c56.jpg)

The URL displayed when the error appears is "http://songshark,kitamuracomputers.net:8080/login"

The log doesn't show anything weird, only this:

Successfully released change log lock
Automatic media library scanning scheduled to run every 1 day(s), starting at Tue May 30 03:00:00 BST 2017
Media library never scanned. Doing it now.
Starting to scan media library.
Automatic Podcast update scheduled to run every 24 hour(s), starting at Tue May 30 00:40:11 BST 2017
Starting UPnP service...
Scanned media library with 0 entries.
Marking non-present files.
Marking non-present artists.
Marking non-present albums.
Completed media library scan.
Starting playlist import.
Completed playlist import.
Disabling UPnP/DLNA media server
Starting UPnP service - Done!
Started Application in 50.433 seconds (JVM running for 51.95)
Starting scheduled Podcast refresh.
Completed scheduled Podcast refresh.
Servlet container: Apache Tomcat/8.5.11

If it helps I'm booting the server standalone with a BAT file which contains the line "java -jar libresonic.war". I have a local TomCat server on a different port (8082) but that's v6 and not v8 which LibreSonic reports.

**Comment by muff1nman** [comment]
Can you try clearing your browser cache? Or a hard refresh on chrome, control-shift-r?

**Comment by muff1nman** [comment]
![screenshot_20170529-183537](https://cloud.githubusercontent.com/assets/1531528/26564422/af454302-449d-11e7-8660-84adb90e6aa3.png)

I got in fine ;)

**Comment by SuperNerd-James** [comment]
Damn it! I feel silly now, but something is going on.

Outside the network If I have a tab open with my SongShark branded SubSonic on port 8081 running, the LibreSonic on 8080 throws the error. If I close the SubSonic tab, it works? Is it a cookie clash?

**Comment by muff1nman** [comment]
There's a very good possibility there could be some cookie clash. But that would be something separate to investigate in a different issue. So can we close this now?

**Comment by SuperNerd-James** [comment]
I guess so! *feels embarrassed*

**Comment by muff1nman** [comment]
No worries just glad to clear up any confusion ;)
