### ISSUE TITLE
403 Forbidden - CRSF Tocken don't work without cookies

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#449]
While helping a friend setting up his Libresonic account, we faced a 403 Forbidden.

I think this is related to the CRSF Token system who needs cookies.
After reenabling cookies the login worked just fine.
Didn't found any logs.

Here is the screen: 
![capture d ecran de 2017-05-31 17-56-43](https://cloud.githubusercontent.com/assets/19195485/26642662/e4e810ce-462e-11e7-8b02-82d96b3f7966.png)

**Comment by SuperNerd-James** [comment]
I can also confirm this happens when running two tabs in browser, each for separate installations, even when cookies are enabled, it's like the cookies for each install clash with each other. I discovered it during #443 as I run SubSonic and the develop version of LibreSonic on the same server, they can't be run together in a browser.

**Comment by muff1nman** [comment]
Cookies are required to use libresonic web interface.

**Comment by jooola** [comment]
Wait ! We need it but ending on a 403 isn't clean at all...

Maybe create a page or write it somewhere ...

Fine let's leave this closed ...

**Comment by muff1nman** [comment]
Yes it's very expected. 403 says permission denied which is exactly the message we should send if you don't give us the cookie.
