### ISSUE TITLE
Libresonic Specific API

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#467]
I think this is a good topic for IRC, but would like to get some extra visibility and @biconou s opinion
```
08:12:27 muff1nman Anyone have any opinions on how the libresonic-specific rest api should be implemented? I'm curious to hear anyones thoughts
08:14:33 muff1nman Currently I'm thinking we improve the authentication and dont use the same auth as the old api
08:15:14 muff1nman Also we should use the built-in serialization capabilities of spring rather than handrolling it like is done in the subsonic rest endpoint
08:15:39 muff1nman Also I'm thinking we make it so that it can be used by itself
08:15:59 muff1nman To avoid folks from having to talk with both the subsonic rest api and the libresonic rest api
08:16:17 muff1nman so we would copy over all of the existing methods with some cleanups
08:18:36 muff1nman Im thinking we put it at a different endpoint than /rest
08:18:38 muff1nman perhaps /api
08:18:53 muff1nman wheres biconou?
```

**Comment by biconou** [comment]
agree with "use the built-in serialization capabilities of spring ".
I completely agree with creating a new endpoint (/api).

I would have preferred a better designed REST api. I mean using resources ids in urls and real http methods schemes.
We clould have the legacy subsonic API compatibility and a Libresonic API having the sames services plus Libresonic specifics with a better design. 
But it will be a lot of work. 
Sometimes I think it could worth doing because REST apis are extremely popular nowadays. 

I also started some experiments to be able to use a REST api design framework. I started with RAML.
Swagger would also be cool.
