### ISSUE TITLE
Move to new namespace

### ISSUE THREAD

**Issue by csobsidian** [Libresonic/libresonic#52]
Eugene has suggested a move to org.libresonic.player

Other suggestions? Implications?

**Comment by stevenroose** [comment]
This can easily be done by a replace all, right?

**Comment by EugeneKay** [comment]
At present, most of the source files contain a [copyright header](https://github.com/Libresonic/libresonic/blob/develop/subsonic-main/src/test/java/net/sourceforge/subsonic/controller/StreamControllerTestCase.java#L1). These headers should be changed at the same time as this namespace move, since that is the point at which it will cease to be "rebranded Subsonic".

We will need to create an AUTHORS document with a list of contributors(merged commits). The headers will need to be modified:

```
 This file is part of Libresonic.

 Libresonic is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

 Libresonic is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with Libresonic.  If not, see <http://www.gnu.org/licenses/>.

Based upon Subsonic, Copyright 2009 (C) Sindre Mehus
Copyright <Current Year> (C) Libresonic Authors
```

Disclaimer: I Am Not A Lawyer, but I do have enough experience with FOSS licenses to form strong opinions. Please contact me by email if you would like to provide pro bono legal services, but I will need to see your Law Degree first. ;-)

**Comment by EugeneKay** [comment]
7459692 is a massive search+replace of Subsonic-->Libresonic. It does build, but the webapp does not load with a theme error.

**Comment by EugeneKay** [comment]
7b8e07d fixes the theme error.

**Comment by EugeneKay** [comment]
294f390 updates the copyright headers and completes this Issue.
