### ISSUE TITLE
Support for external databases

### ISSUE THREAD

**Issue by joshuaboniface** [Libresonic/libresonic#62]
(my funny story) I was planning to move away from Subsonic right before the announcement, because of just this reason, but after trying the alternatives (mainly Ampache, which due to old DB code turned into a nightmare) I've decided to stick it out with Subsonic and hope you guys can keep an OSS version going!

I'd like to request support for external databases. My music collection is up to 1.7TB, and the Subsonic database file is over 350MB. Since it hit ~1.3TB, I've been getting random occurrences of database corruption, often after an unclean shutdown (not ideal, of course, but this shouldn't be killing the DB IMO). If this happens, I lose not just the library (which takes ~4h to import) but also any starred tracks, etc.

I've written a hacky backup script to help with this, but ultimately, having a true RDBMS backend (e.g. MySQL or Postgres even, though I prefer MariaDB personally), something ACID compliant, rather than a big flat file database prone to corruption, would help immensely.

**Comment by fxthomas** [comment]
This has been on my wishlist ever since I started using Subsonic. It's so damn horrible to get data out of HSQLDB... I will not be able to work on this before mid-june, but count me in if needed!

**Comment by tobiasnix** [comment]
Not sure if its the right time but i just added a [bountysource](https://www.bountysource.com/issues/34086570-support-for-external-databases) to this issue.

**Comment by bajansen** [comment]
I have started work on providing support for external databases. I think I've ironed out the major kinks, but it could do with some more testing. You can try it out via my fork and its externaldb branch. You can configure your own database in the `MysqlDaoHelper.java` file. I'm currently using a mariadb driver and a mariadb database, but MySQL should work as well.

Note that you should run `mvn package -Dmaven.test.skip=true` to skip the database checks while building.

**Comment by danielreuther** [comment]
Yes, this would be a major improvement!

Here's a branch that Sindre has apparently worked on in the past -- it may be valuable to double check how he approached it:
https://github.com/daneren2005/Subsonic-Plus-Mainline/commits/mysql

**Comment by biconou** [comment]
I previously realised a little fix to use an external HsqlDB standalone server rather than the embedded hsqldb. Unfortunately, it's slower. 
I finally keped the embedded database but created a cron script that stops subsonic and compacts the database  every night.

**Comment by muff1nman** [comment]
Ya so this just became a huge thing for me as my hsqldb on my main server got corrupted somehow :(

**Comment by bajansen** [comment]
I have a fork with a working externaldb branch that you are very welcome to test. It mostly works but is not yet user configurable and needs more testing.

**Comment by joshuaboniface** [comment]
I'd be willing to test it out. All I know about building is the basics from the INSTALL page; how would I configure it from your repo? By default I get a lot of errors about not terminating JDBC connections until Tomcat kills the app.

**Comment by bajansen** [comment]
I only just saw you already figured it out, but this reply might still help other interested testers.

You should configure your database settings in the `libresonic/libresonic-main/src/main/java/org/libresonic/player/dao/MyqlDaoHelper.java` file in the `createDataSource()` function. You should create a database and database user for libresonic in advance. Libresonic will automatically populate the database.
I am currently using a mariadb driver but it will work with MySQL itself just as well. When you have configured your database settings you should be able to build and run libresonic as usual.

**Comment by joshuaboniface** [comment]
I seem to be running into a conundrum with my character sets. With the default for MariaDB (latin1_swedish_ci), I get the error:

> org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select id, path, folder, type, format, title, album, artist, album_artist, disc_number, track_number, year, genre, bit_rate,
 variable_bit_rate, duration_seconds, file_size, width, height, cover_art_path, parent_path, play_count, last_played, comment, created, changed, last_scanned, children_last_updated, present, version from media_file where path=?]; SQL state
 [HY000]; error code [1267]; Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
Query is: select id, path, folder, type, format, title, album, artist, album_artist, disc_number, track_number, year, genre, bit_rate, variable_bit_rate, duration_seconds, file_size, width, height, cover_art_path, parent_path, play_count,
last_played, comment, created, changed, last_scanned, children_last_updated, present, version from media_file where path=?; nested exception is java.sql.BatchUpdateException: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8
_general_ci,COERCIBLE) for operation '='

However, if I create my database with UTF (utf8_common_ci), I get the following:

[2016-11-19 00:20:29,591] ERROR MysqlDaoHelper - Failed to initialize database.
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE user (
  username           VARCHAR(256)          NOT NULL PRIMARY KEY,
  password           VARCHAR(256)          NOT NULL,
  bytes_streamed     BIGINT DEFAULT 0      NOT NULL,
  bytes_downloaded   BIGINT DEFAULT 0      NOT NULL,
  bytes_uploaded     BIGINT DEFAULT 0      NOT NULL,
  ldap_authenticated BOOLEAN DEFAULT FALSE NOT NULL,
  email              VARCHAR(256)) ROW_FORMAT=DYNAMIC]; nested exception is java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes

I've determined that the key that's too long is the 256-length VARCHAR; there's an SO post with a similar issue which suggests changing them to 255 instead, but I'm curious if I'm just setting the wrong encoding?

(Can provide full stack traces from libresonic.log if you wish).

**Comment by bajansen** [comment]
Yeah I forgot that you will have to create a database with support for utf8 and large prefixes. Because UTF8 strings require 4 bytes for each character the 256-length VARCHARs makes the columns exceed the MySQL size limit. A workaround would be to reduce the length of the VARCHARs, but this will cause problems for files with long file- or artist names.

On my test machine I was running mariadb with barracuda as the innodb file format and the option `one_file_per_table` but these are probably not explicitly required.

**Comment by joshuaboniface** [comment]
Thanks! That got me through database creation and I was able to log in, but scanning the library dropped a NullPointerException with little other detail:

>[2016-11-19 13:30:26,460] INFO MediaScannerService - Starting to scan media library.
[2016-11-19 13:30:40,450] ERROR MediaScannerService - Failed to scan media library.
java.lang.NullPointerException
        at org.libresonic.player.dao.MediaFileDao.createOrUpdateMediaFile(MediaFileDao.java:192)
        at org.libresonic.player.service.MediaFileService.updateChildren(MediaFileService.java:396)
        at org.libresonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:194)
        at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:238)
        at org.libresonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:180)
        at org.libresonic.player.service.MediaScannerService.access$000(MediaScannerService.java:50)
        at org.libresonic.player.service.MediaScannerService$2.run(MediaScannerService.java:149)
[2016-11-19 13:30:40,511] INFO PlaylistService - Starting playlist import.
[2016-11-19 13:30:40,511] INFO PlaylistService - Completed playlist import.

**Comment by muff1nman** [comment]
@bajansen Thanks for working on this. I read over what you have so far, and here are my first thoughts:
- I think its going to become cumbersome real fast deal with versioning multiple databases using straight sql. Maybe we need to adopt somethink like liquibase so we can keep track of these better?
- Can we completely axe the concept of vendor specific DaoHelper(s)? I think if we expose the jdbc connection properties to the user to configure, we can connect via jdbc in a vendor neutral way. The only issue would be the jdbc drivers being on the classpath. Maybe we can keep the hsqldb dependency, but don't add any other jdbc drivers. Users that want to change their database would then have to ensure the jdbc driver is on the classpath. Easy enough for tomcat by throwing it in the lib directory.

Thoughts?

**Comment by bajansen** [comment]
@muff1nman These points are exactly what I ran into while fooling around with this database stuff. The current state of the externaldb branch is basically code that Sindre wrote at some point for mysql support that didn't make it into mainline subsonic (at least not version 5.3). The SQL file is probably only suited to introduce the initial MySQL support and any database changes that come with newer Libresonic versions will probably have to be introduced in the same way HSQL is updated. With the current state of Libresonic that is.

It would definitely be better to handle the database stuff outside of Libresonic. The way it is set up now, at least for the standalone application, database parameters will probably have to be handed to libresonic as command line arguments which could probably lead to the parameters being visible to other applications.

**Comment by joshuaboniface** [comment]
Command-line arguments are likely a very bad idea (db password in 'ps' output), but a config file is a pretty standard way of passing those parameters. I don't think Sub/Libresonic currently has a dedicated config file, but perhaps it should? The question of where to put it ("/var/libresonic" like the DB, perhaps?) and how to implement it are outside of my personal scope as an advanced user though :)

**Comment by bajansen** [comment]
The current configuration files for standalone Libresonic are `/etc/default/libresonic` and `/var/libresonic/libresonic.properties`. This second file is only read at a later point during startup, _after_ the database is initialized. The other config file on the other hand passes all options as command line arguments to the actual application. To read database parameters from a file, a third configuration file would have to be read, and a way to read this file at initial startup will have to be implemented. This means it would probably better to change the way databases are handled entirely.

**Comment by joshuaboniface** [comment]
What sort of changes would be needed for that? I'm not a Java developer, but I do know enough Java and have enough time and motivation to try to hack something together. To be specific I'm not sure what you mean by moving the database "outside of Libresonic"?

**Comment by muff1nman** [comment]
Okay so it sounds like we have two main challenges:
1. How to manage database configurations
2. How to manage database change sets across multiple database vendors

For 2. I think one idea is to make it so that the config file in /var/libresonic/libresonic.properties is read before the database is initialized.

For 1. I think we could either go with the current path or spend a bit of time seeing if we can utilize liquibase or similar tool. There are some other challenges with migrating to an external tool, such as integrating it with the subsonic runtime. My experience with liquibase has been with using it outside of the application, but I think it would be good to keep it integrated with the application runtime.

I'll see if I can spend a bit of time with 2, because I think it will be necessary no matter what and to give a bit more time to think on 1. I don't mean to step on any toes here, so apologies in advance @bajansen if I have, but just really want to help get this moving as my libresonic is down. Definitely would like to collaborate on a shared branch.

**Comment by bajansen** [comment]
I'm not really able to put a lot of time into Libresonic right now so anyone who wants to contribute is more than welcome. Also I am not exactly a Java developer so any suggestions for improvement or refactoring are very welcome as well.

**Comment by biconou** [comment]
@muff1nman Implementing liquibase would be very classy.

**Comment by zifnab06** [comment]
jetty and tomcat both have support for jbdc connection pools - is there any reason to re-invent the wheel here? 

https://tomcat.apache.org/tomcat-7.0-doc/jndi-datasource-examples-howto.html
https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html

**Comment by biconou** [comment]
@zifnab06 What do you mean ? liquibase is about database model evolution tracking, not connection pooling (I may be wrong of course).

**Comment by muff1nman** [comment]
So a couple of decisions to be made about this and I'm curious as to how people feel about the following topics:

### Connection specification
1. Specify jdbc connection via libresonic.properties
2. Rely on jndi lookup from container for jdbc connection
3. Do both and let the user choose which lookup mechanism via a property in libresonic.properties

I was originally thinking just 2, as it offers the greatest flexibility and allows the user to supply the database jdbc driver. Its also recommended by [spring](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-connect-to-production-database). However, for spring boot, I'm not sure jndi makes as much sense and perhaps 1 makes more sense there. However, then we have to worry about the jdbc driver being on the classpath. In the end, perhaps I'll go with 3 - a bit more complicated, but most flexible.

### Hsql
Continuing from above, I'd like to consider to stop shipping the hsql jdbc driver with libresonic. Its not reliable and is outdated. But perhaps if we do that, we need a wiki or something to guide people on selecting a jdbc driver, and migrating between databases?

### Auto Liquibase migration
Previously, subsonic did the database migrations on application startup. I have liquibase setup such that it will do this, but I'm a bit hesitant about keeping it this way. Especially since we have opened the door for other databases, there is a much higher chance of a migration failure. Really we need people to backup their database before doing a migration with a new version of libresonic. Perhaps we can prevent the migration until folks have acknowledged that they have taken the necessary steps to protect their data. Thoughts?

Current status: not ready for testing. I will submit a PR when it is. Right now I have hsqldb 1.8.0.10 somewhat working. I am going to do a schema comparison to see how it compares to the old Schema java class migration mechanism. Then, I'm going to test other databases. My biggest concern is with the lack of varchar length specification on our columns which so far has caused problems with hsqldb > 2. Worst case, is that I'll have to go through all the varchar columns and assign lengths.

**Comment by EugeneKay** [comment]
What would a new-install and upgrade-migrate look like with Option 3?

I think this should require as little intervention as possible. Eg, if nothing is specified in libresonic.properties then it should first look for a sqlite(?) local database and create it if not found; if there is an empty database(eg, via JDBC or a brand-new local db) then attempt to import from Hsql.

**Comment by muff1nman** [comment]
If we want to have minimal effort for new-install and upgrade-migrate I think we should continue to bundle hsqldb 1.8 in libresonic and then default to using the same datasource as before specified via default jdbc.url/jdbc.username/jdbc.password property files (overrideable of course). In addition, we should continue to do auto liquibase migrations.

If all of that is done, the user won't even notice a thing..

**Comment by biconou** [comment]
Some remarks : 

We must consider here the probably new form of packaging that SpringBoot will bring.
Using SpringBoot we will be able to package the application as both a all-in-one jar or a war to deploy to a servlet container.

I don't understand the problem with shipping the jdbc drive ? It will complicate the installation process and we are on the way to simplify it with SpringBoot.

I would prefer Liquibase rather the current system.

**Comment by muff1nman** [comment]
Put PR #172 out there - needs some more testing though.

I kept the hsql jdbc driver in there, but I would rather not package all possible jdbc drivers that might work. Perhaps we could make separate builds for specific jdbc drivers if there is interest.

**Comment by alexfornuto** [comment]
> I finally keped the embedded database but created a cron script that stops subsonic and compacts the database every night.

@biconou Would you mind sharing this script?

**Comment by muff1nman** [comment]
#172 is now in the develop branch. Backup your database and try it out. Open an issue if you run into any problems.
